2025-07-01T21:37:10.755+05:30  INFO 45607 --- [SMS-Utility] [main] c.e.SMS.Utility.SmsUtilityApplication    : Starting SmsUtilityApplication using Java 21.0.5 with PID 45607 (/Users/sakshamvaishya/Downloads/SMS-Utility/target/classes started by sakshamvaishya in /Users/sakshamvaishya/Downloads/SMS-Utility)
2025-07-01T21:37:10.768+05:30 DEBUG 45607 --- [SMS-Utility] [main] c.e.SMS.Utility.SmsUtilityApplication    : Running with Spring Boot v3.5.3, Spring v6.2.8
2025-07-01T21:37:10.769+05:30  INFO 45607 --- [SMS-Utility] [main] c.e.SMS.Utility.SmsUtilityApplication    : No active profile set, falling back to 1 default profile: "default"
2025-07-01T21:37:11.179+05:30  INFO 45607 --- [SMS-Utility] [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2025-07-01T21:37:11.258+05:30  INFO 45607 --- [SMS-Utility] [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 74 ms. Found 2 JPA repository interfaces.
2025-07-01T21:37:11.584+05:30  INFO 45607 --- [SMS-Utility] [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8080 (http)
2025-07-01T21:37:11.593+05:30  INFO 45607 --- [SMS-Utility] [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2025-07-01T21:37:11.593+05:30  INFO 45607 --- [SMS-Utility] [main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.42]
2025-07-01T21:37:11.638+05:30  INFO 45607 --- [SMS-Utility] [main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2025-07-01T21:37:11.638+05:30  INFO 45607 --- [SMS-Utility] [main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 826 ms
2025-07-01T21:37:11.769+05:30  INFO 45607 --- [SMS-Utility] [main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2025-07-01T21:37:11.804+05:30  INFO 45607 --- [SMS-Utility] [main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 6.6.18.Final
2025-07-01T21:37:11.828+05:30  INFO 45607 --- [SMS-Utility] [main] o.h.c.internal.RegionFactoryInitiator    : HHH000026: Second-level cache disabled
2025-07-01T21:37:11.995+05:30  INFO 45607 --- [SMS-Utility] [main] o.s.o.j.p.SpringPersistenceUnitInfo      : No LoadTimeWeaver setup: ignoring JPA class transformer
2025-07-01T21:37:12.021+05:30  INFO 45607 --- [SMS-Utility] [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2025-07-01T21:37:12.180+05:30  INFO 45607 --- [SMS-Utility] [main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@671da0f9
2025-07-01T21:37:12.181+05:30  INFO 45607 --- [SMS-Utility] [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2025-07-01T21:37:12.232+05:30  INFO 45607 --- [SMS-Utility] [main] org.hibernate.orm.connections.pooling    : HHH10001005: Database info:
	Database JDBC URL [Connecting through datasource 'HikariDataSource (HikariPool-1)']
	Database driver: undefined/unknown
	Database version: 17.2
	Autocommit mode: undefined/unknown
	Isolation level: undefined/unknown
	Minimum pool size: undefined/unknown
	Maximum pool size: undefined/unknown
2025-07-01T21:37:12.670+05:30  INFO 45607 --- [SMS-Utility] [main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000489: No JTA platform available (set 'hibernate.transaction.jta.platform' to enable JTA platform integration)
2025-07-01T21:37:12.743+05:30  INFO 45607 --- [SMS-Utility] [main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2025-07-01T21:37:12.882+05:30  INFO 45607 --- [SMS-Utility] [main] o.s.d.j.r.query.QueryEnhancerFactory     : Hibernate is in classpath; If applicable, HQL parser will be used.
2025-07-01T21:37:13.021+05:30  INFO 45607 --- [SMS-Utility] [main] com.example.SMS.Utility.config.Config    : corePoolSize:-15, maxPoolSize:-20,queueCapacity:-30
2025-07-01T21:37:13.075+05:30  WARN 45607 --- [SMS-Utility] [main] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
2025-07-01T21:37:13.259+05:30  INFO 45607 --- [SMS-Utility] [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port 8080 (http) with context path '/'
2025-07-01T21:37:13.267+05:30  INFO 45607 --- [SMS-Utility] [main] c.e.SMS.Utility.SmsUtilityApplication    : Started SmsUtilityApplication in 2.849 seconds (process running for 3.26)
2025-07-01T21:37:31.883+05:30  INFO 45607 --- [SMS-Utility] [SpringApplicationShutdownHook] o.s.b.w.e.tomcat.GracefulShutdown        : Commencing graceful shutdown. Waiting for active requests to complete
2025-07-01T21:37:31.889+05:30  INFO 45607 --- [SMS-Utility] [tomcat-shutdown] o.s.b.w.e.tomcat.GracefulShutdown        : Graceful shutdown complete
2025-07-01T21:37:31.945+05:30  INFO 45607 --- [SMS-Utility] [scheduling-1] c.e.SMS.Utility.service.SMSScheduler     : No pending SMS to send to the user.
2025-07-01T21:37:31.957+05:30  INFO 45607 --- [SMS-Utility] [SpringApplicationShutdownHook] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2025-07-01T21:37:31.958+05:30  INFO 45607 --- [SMS-Utility] [SpringApplicationShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2025-07-01T21:37:31.960+05:30  INFO 45607 --- [SMS-Utility] [SpringApplicationShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2025-07-01T21:37:49.512+05:30  INFO 45647 --- [SMS-Utility] [main] c.e.SMS.Utility.SmsUtilityApplication    : Starting SmsUtilityApplication using Java 21.0.5 with PID 45647 (/Users/sakshamvaishya/Downloads/SMS-Utility/target/classes started by sakshamvaishya in /Users/sakshamvaishya/Downloads/SMS-Utility)
2025-07-01T21:37:49.513+05:30 DEBUG 45647 --- [SMS-Utility] [main] c.e.SMS.Utility.SmsUtilityApplication    : Running with Spring Boot v3.5.3, Spring v6.2.8
2025-07-01T21:37:49.514+05:30  INFO 45647 --- [SMS-Utility] [main] c.e.SMS.Utility.SmsUtilityApplication    : No active profile set, falling back to 1 default profile: "default"
2025-07-01T21:37:49.919+05:30  INFO 45647 --- [SMS-Utility] [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2025-07-01T21:37:49.997+05:30  INFO 45647 --- [SMS-Utility] [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 73 ms. Found 2 JPA repository interfaces.
2025-07-01T21:37:50.316+05:30  INFO 45647 --- [SMS-Utility] [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8080 (http)
2025-07-01T21:37:50.324+05:30  INFO 45647 --- [SMS-Utility] [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2025-07-01T21:37:50.324+05:30  INFO 45647 --- [SMS-Utility] [main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.42]
2025-07-01T21:37:50.359+05:30  INFO 45647 --- [SMS-Utility] [main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2025-07-01T21:37:50.359+05:30  INFO 45647 --- [SMS-Utility] [main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 819 ms
2025-07-01T21:37:50.446+05:30  INFO 45647 --- [SMS-Utility] [main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2025-07-01T21:37:50.476+05:30  INFO 45647 --- [SMS-Utility] [main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 6.6.18.Final
2025-07-01T21:37:50.495+05:30  INFO 45647 --- [SMS-Utility] [main] o.h.c.internal.RegionFactoryInitiator    : HHH000026: Second-level cache disabled
2025-07-01T21:37:50.674+05:30  INFO 45647 --- [SMS-Utility] [main] o.s.o.j.p.SpringPersistenceUnitInfo      : No LoadTimeWeaver setup: ignoring JPA class transformer
2025-07-01T21:37:50.692+05:30  INFO 45647 --- [SMS-Utility] [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2025-07-01T21:37:50.833+05:30  INFO 45647 --- [SMS-Utility] [main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@965bcbc
2025-07-01T21:37:50.834+05:30  INFO 45647 --- [SMS-Utility] [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2025-07-01T21:37:50.871+05:30  INFO 45647 --- [SMS-Utility] [main] org.hibernate.orm.connections.pooling    : HHH10001005: Database info:
	Database JDBC URL [Connecting through datasource 'HikariDataSource (HikariPool-1)']
	Database driver: undefined/unknown
	Database version: 17.2
	Autocommit mode: undefined/unknown
	Isolation level: undefined/unknown
	Minimum pool size: undefined/unknown
	Maximum pool size: undefined/unknown
2025-07-01T21:37:51.337+05:30  INFO 45647 --- [SMS-Utility] [main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000489: No JTA platform available (set 'hibernate.transaction.jta.platform' to enable JTA platform integration)
2025-07-01T21:37:51.369+05:30  INFO 45647 --- [SMS-Utility] [main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2025-07-01T21:37:51.507+05:30  INFO 45647 --- [SMS-Utility] [main] o.s.d.j.r.query.QueryEnhancerFactory     : Hibernate is in classpath; If applicable, HQL parser will be used.
2025-07-01T21:37:51.640+05:30  INFO 45647 --- [SMS-Utility] [main] com.example.SMS.Utility.config.Config    : corePoolSize:-4, maxPoolSize:-4,queueCapacity:-0
2025-07-01T21:37:51.699+05:30  WARN 45647 --- [SMS-Utility] [main] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
2025-07-01T21:37:51.895+05:30  INFO 45647 --- [SMS-Utility] [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port 8080 (http) with context path '/'
2025-07-01T21:37:51.902+05:30  INFO 45647 --- [SMS-Utility] [main] c.e.SMS.Utility.SmsUtilityApplication    : Started SmsUtilityApplication in 2.692 seconds (process running for 3.078)
2025-07-01T21:38:27.674+05:30  INFO 45647 --- [SMS-Utility] [scheduling-1] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 1, using thread:- scheduling-1
2025-07-01T21:38:45.601+05:30 ERROR 45647 --- [SMS-Utility] [scheduling-1] i.n.r.d.DnsServerAddressStreamProviders  : Unable to load io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS. Check whether you have a dependency on 'io.netty:netty-resolver-dns-native-macos'. Use DEBUG level to see the full stack: java.lang.UnsatisfiedLinkError: failed to load the required native library
2025-07-01T21:38:45.895+05:30  INFO 45647 --- [SMS-Utility] [scheduling-1] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 2, using thread:- scheduling-1
2025-07-01T21:38:45.898+05:30  INFO 45647 --- [SMS-Utility] [SMS-Thread-3] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 3, using thread:- SMS-Thread-3
2025-07-01T21:38:45.899+05:30  INFO 45647 --- [SMS-Utility] [SMS-Thread-4] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 4, using thread:- SMS-Thread-4
2025-07-01T21:38:45.899+05:30  INFO 45647 --- [SMS-Utility] [SMS-Thread-1] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 5, using thread:- SMS-Thread-1
2025-07-01T21:38:45.899+05:30  INFO 45647 --- [SMS-Utility] [SMS-Thread-2] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 8, using thread:- SMS-Thread-2
2025-07-01T21:38:45.899+05:30  INFO 45647 --- [SMS-Utility] [scheduling-1] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 10, using thread:- scheduling-1
2025-07-01T21:38:45.902+05:30  INFO 45647 --- [SMS-Utility] [SMS-Thread-4] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 12, using thread:- SMS-Thread-4
2025-07-01T21:38:45.902+05:30  INFO 45647 --- [SMS-Utility] [SMS-Thread-3] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 13, using thread:- SMS-Thread-3
2025-07-01T21:38:45.902+05:30  INFO 45647 --- [SMS-Utility] [SMS-Thread-2] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 9, using thread:- SMS-Thread-2
2025-07-01T21:38:45.902+05:30  INFO 45647 --- [SMS-Utility] [SMS-Thread-1] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 7, using thread:- SMS-Thread-1
2025-07-01T21:38:45.902+05:30  INFO 45647 --- [SMS-Utility] [SMS-Thread-4] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 14, using thread:- SMS-Thread-4
2025-07-01T21:38:45.903+05:30  INFO 45647 --- [SMS-Utility] [SMS-Thread-3] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 11, using thread:- SMS-Thread-3
2025-07-01T21:38:45.903+05:30  INFO 45647 --- [SMS-Utility] [SMS-Thread-2] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 6, using thread:- SMS-Thread-2
2025-07-01T21:39:30.351+05:30  WARN 45647 --- [SMS-Utility] [HikariPool-1:housekeeper] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m2s681ms).
2025-07-01T21:39:34.042+05:30 ERROR 45647 --- [SMS-Utility] [reactor-http-nio-1] c.e.SMS.Utility.service.SMSService       : While processing the rows error throwing:- 500 Internal Server Error from POST http://localhost:9090/api/v1/message
2025-07-01T21:39:34.042+05:30 ERROR 45647 --- [SMS-Utility] [reactor-http-nio-6] c.e.SMS.Utility.service.SMSService       : While processing the rows error throwing:- 404 Not Found from POST http://localhost:9090/api/v1/message
2025-07-01T21:39:34.043+05:30 ERROR 45647 --- [SMS-Utility] [reactor-http-nio-8] c.e.SMS.Utility.service.SMSService       : While processing the rows error throwing:- 500 Internal Server Error from POST http://localhost:9090/api/v1/message
2025-07-01T21:39:34.051+05:30 ERROR 45647 --- [SMS-Utility] [reactor-http-nio-6] c.e.SMS.Utility.service.SMSScheduler     : Time out occurred while waiting for future: org.springframework.web.reactive.function.client.WebClientResponseException$NotFound: 404 Not Found from POST http://localhost:9090/api/v1/message
2025-07-01T21:41:15.278+05:30  WARN 45647 --- [SMS-Utility] [HikariPool-1:housekeeper] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m44s928ms).
2025-07-01T21:41:18.207+05:30  INFO 45647 --- [SMS-Utility] [SMS-Thread-4] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 10, using thread:- SMS-Thread-4
2025-07-01T21:41:18.207+05:30  INFO 45647 --- [SMS-Utility] [SMS-Thread-1] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 8, using thread:- SMS-Thread-1
2025-07-01T21:41:18.207+05:30  INFO 45647 --- [SMS-Utility] [SMS-Thread-3] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 11, using thread:- SMS-Thread-3
2025-07-01T21:41:18.207+05:30  INFO 45647 --- [SMS-Utility] [SMS-Thread-2] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 13, using thread:- SMS-Thread-2
2025-07-01T21:47:54.420+05:30  WARN 45647 --- [SMS-Utility] [HikariPool-1:housekeeper] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=6m39s141ms).
2025-07-01T21:47:54.519+05:30  INFO 45647 --- [SMS-Utility] [SpringApplicationShutdownHook] o.s.b.w.e.tomcat.GracefulShutdown        : Commencing graceful shutdown. Waiting for active requests to complete
2025-07-01T21:47:54.523+05:30  INFO 45647 --- [SMS-Utility] [tomcat-shutdown] o.s.b.w.e.tomcat.GracefulShutdown        : Graceful shutdown complete
2025-07-01T21:47:54.550+05:30 ERROR 45647 --- [SMS-Utility] [reactor-http-nio-8] c.e.SMS.Utility.service.SMSService       : While processing the rows error throwing:- 404 Not Found from POST http://localhost:9090/api/v1/message
2025-07-01T21:47:54.550+05:30 ERROR 45647 --- [SMS-Utility] [reactor-http-nio-1] c.e.SMS.Utility.service.SMSService       : While processing the rows error throwing:- 500 Internal Server Error from POST http://localhost:9090/api/v1/message
2025-07-01T21:47:54.550+05:30 ERROR 45647 --- [SMS-Utility] [reactor-http-nio-7] c.e.SMS.Utility.service.SMSService       : While processing the rows error throwing:- 500 Internal Server Error from POST http://localhost:9090/api/v1/message
2025-07-01T21:47:54.551+05:30 ERROR 45647 --- [SMS-Utility] [reactor-http-nio-7] c.e.SMS.Utility.service.SMSScheduler     : Time out occurred while waiting for future: org.springframework.web.reactive.function.client.WebClientResponseException$InternalServerError: 500 Internal Server Error from POST http://localhost:9090/api/v1/message
2025-07-01T21:47:56.641+05:30  INFO 45647 --- [SMS-Utility] [SpringApplicationShutdownHook] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2025-07-01T21:47:56.645+05:30  INFO 45647 --- [SMS-Utility] [SpringApplicationShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2025-07-01T21:47:56.647+05:30  INFO 45647 --- [SMS-Utility] [SpringApplicationShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2025-07-01T21:47:58.942+05:30  INFO 45924 --- [SMS-Utility] [main] c.e.SMS.Utility.SmsUtilityApplication    : Starting SmsUtilityApplication using Java 21.0.5 with PID 45924 (/Users/sakshamvaishya/Downloads/SMS-Utility/target/classes started by sakshamvaishya in /Users/sakshamvaishya/Downloads/SMS-Utility)
2025-07-01T21:47:58.943+05:30 DEBUG 45924 --- [SMS-Utility] [main] c.e.SMS.Utility.SmsUtilityApplication    : Running with Spring Boot v3.5.3, Spring v6.2.8
2025-07-01T21:47:58.944+05:30  INFO 45924 --- [SMS-Utility] [main] c.e.SMS.Utility.SmsUtilityApplication    : No active profile set, falling back to 1 default profile: "default"
2025-07-01T21:47:59.363+05:30  INFO 45924 --- [SMS-Utility] [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2025-07-01T21:47:59.447+05:30  INFO 45924 --- [SMS-Utility] [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 76 ms. Found 2 JPA repository interfaces.
2025-07-01T21:47:59.818+05:30  INFO 45924 --- [SMS-Utility] [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8080 (http)
2025-07-01T21:47:59.827+05:30  INFO 45924 --- [SMS-Utility] [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2025-07-01T21:47:59.827+05:30  INFO 45924 --- [SMS-Utility] [main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.42]
2025-07-01T21:47:59.862+05:30  INFO 45924 --- [SMS-Utility] [main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2025-07-01T21:47:59.862+05:30  INFO 45924 --- [SMS-Utility] [main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 879 ms
2025-07-01T21:47:59.951+05:30  INFO 45924 --- [SMS-Utility] [main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2025-07-01T21:47:59.980+05:30  INFO 45924 --- [SMS-Utility] [main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 6.6.18.Final
2025-07-01T21:47:59.997+05:30  INFO 45924 --- [SMS-Utility] [main] o.h.c.internal.RegionFactoryInitiator    : HHH000026: Second-level cache disabled
2025-07-01T21:48:00.167+05:30  INFO 45924 --- [SMS-Utility] [main] o.s.o.j.p.SpringPersistenceUnitInfo      : No LoadTimeWeaver setup: ignoring JPA class transformer
2025-07-01T21:48:00.182+05:30  INFO 45924 --- [SMS-Utility] [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2025-07-01T21:48:00.316+05:30  INFO 45924 --- [SMS-Utility] [main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@7db47323
2025-07-01T21:48:00.317+05:30  INFO 45924 --- [SMS-Utility] [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2025-07-01T21:48:00.358+05:30  INFO 45924 --- [SMS-Utility] [main] org.hibernate.orm.connections.pooling    : HHH10001005: Database info:
	Database JDBC URL [Connecting through datasource 'HikariDataSource (HikariPool-1)']
	Database driver: undefined/unknown
	Database version: 17.2
	Autocommit mode: undefined/unknown
	Isolation level: undefined/unknown
	Minimum pool size: undefined/unknown
	Maximum pool size: undefined/unknown
2025-07-01T21:48:00.811+05:30  INFO 45924 --- [SMS-Utility] [main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000489: No JTA platform available (set 'hibernate.transaction.jta.platform' to enable JTA platform integration)
2025-07-01T21:48:00.855+05:30  INFO 45924 --- [SMS-Utility] [main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2025-07-01T21:48:00.994+05:30  INFO 45924 --- [SMS-Utility] [main] o.s.d.j.r.query.QueryEnhancerFactory     : Hibernate is in classpath; If applicable, HQL parser will be used.
2025-07-01T21:48:01.118+05:30  INFO 45924 --- [SMS-Utility] [main] com.example.SMS.Utility.config.Config    : corePoolSize:-4, maxPoolSize:-4,queueCapacity:-0
2025-07-01T21:48:01.170+05:30  WARN 45924 --- [SMS-Utility] [main] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
2025-07-01T21:48:01.351+05:30  INFO 45924 --- [SMS-Utility] [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port 8080 (http) with context path '/'
2025-07-01T21:48:01.357+05:30  INFO 45924 --- [SMS-Utility] [main] c.e.SMS.Utility.SmsUtilityApplication    : Started SmsUtilityApplication in 2.791 seconds (process running for 3.252)
2025-07-01T21:48:22.351+05:30  INFO 45924 --- [SMS-Utility] [scheduling-1] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 1, using thread:- scheduling-1
2025-07-01T21:48:22.454+05:30 ERROR 45924 --- [SMS-Utility] [scheduling-1] i.n.r.d.DnsServerAddressStreamProviders  : Unable to load io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS. Check whether you have a dependency on 'io.netty:netty-resolver-dns-native-macos'. Use DEBUG level to see the full stack: java.lang.UnsatisfiedLinkError: failed to load the required native library
2025-07-01T21:48:22.501+05:30  INFO 45924 --- [SMS-Utility] [SMS-Thread-2] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 2, using thread:- SMS-Thread-2
2025-07-01T21:48:22.501+05:30  INFO 45924 --- [SMS-Utility] [SMS-Thread-3] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 3, using thread:- SMS-Thread-3
2025-07-01T21:48:22.501+05:30  INFO 45924 --- [SMS-Utility] [SMS-Thread-1] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 5, using thread:- SMS-Thread-1
2025-07-01T21:48:22.501+05:30  INFO 45924 --- [SMS-Utility] [SMS-Thread-4] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 4, using thread:- SMS-Thread-4
2025-07-01T21:48:22.503+05:30 ERROR 45924 --- [SMS-Utility] [scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

org.springframework.core.task.TaskRejectedException: ExecutorService in active state did not accept task: java.util.concurrent.CompletableFuture$AsyncSupply@292dbcfd
	at org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor.execute(ThreadPoolTaskExecutor.java:391) ~[spring-context-6.2.8.jar:6.2.8]
	at java.base/java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1782) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:2005) ~[na:na]
	at com.example.SMS.Utility.service.SMSScheduler.scheduler(SMSScheduler.java:47) ~[classes/:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.runInternal(ScheduledMethodRunnable.java:130) ~[spring-context-6.2.8.jar:6.2.8]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.lambda$run$2(ScheduledMethodRunnable.java:124) ~[spring-context-6.2.8.jar:6.2.8]
	at io.micrometer.observation.Observation.observe(Observation.java:498) ~[micrometer-observation-1.15.1.jar:1.15.1]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:124) ~[spring-context-6.2.8.jar:6.2.8]
	at org.springframework.scheduling.config.Task$OutcomeTrackingRunnable.run(Task.java:85) ~[spring-context-6.2.8.jar:6.2.8]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.2.8.jar:6.2.8]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:358) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.CompletableFuture$AsyncSupply@292dbcfd rejected from org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor$1@14b9817b[Running, pool size = 4, active threads = 4, queued tasks = 0, completed tasks = 1]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2081) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:841) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1376) ~[na:na]
	at org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor$1.execute(ThreadPoolTaskExecutor.java:295) ~[spring-context-6.2.8.jar:6.2.8]
	at org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor.execute(ThreadPoolTaskExecutor.java:388) ~[spring-context-6.2.8.jar:6.2.8]
	... 18 common frames omitted

2025-07-01T21:48:24.430+05:30  INFO 45924 --- [SMS-Utility] [SMS-Thread-2] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 2, using thread:- SMS-Thread-2
2025-07-01T21:48:24.430+05:30  INFO 45924 --- [SMS-Utility] [SMS-Thread-4] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 3, using thread:- SMS-Thread-4
2025-07-01T21:48:24.430+05:30  INFO 45924 --- [SMS-Utility] [SMS-Thread-1] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 4, using thread:- SMS-Thread-1
2025-07-01T21:48:24.430+05:30 ERROR 45924 --- [SMS-Utility] [scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

org.springframework.core.task.TaskRejectedException: ExecutorService in active state did not accept task: java.util.concurrent.CompletableFuture$AsyncSupply@701c4bf8
	at org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor.execute(ThreadPoolTaskExecutor.java:391) ~[spring-context-6.2.8.jar:6.2.8]
	at java.base/java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1782) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:2005) ~[na:na]
	at com.example.SMS.Utility.service.SMSScheduler.scheduler(SMSScheduler.java:47) ~[classes/:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.runInternal(ScheduledMethodRunnable.java:130) ~[spring-context-6.2.8.jar:6.2.8]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.lambda$run$2(ScheduledMethodRunnable.java:124) ~[spring-context-6.2.8.jar:6.2.8]
	at io.micrometer.observation.Observation.observe(Observation.java:498) ~[micrometer-observation-1.15.1.jar:1.15.1]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:124) ~[spring-context-6.2.8.jar:6.2.8]
	at org.springframework.scheduling.config.Task$OutcomeTrackingRunnable.run(Task.java:85) ~[spring-context-6.2.8.jar:6.2.8]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.2.8.jar:6.2.8]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:358) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.CompletableFuture$AsyncSupply@701c4bf8 rejected from org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor$1@14b9817b[Running, pool size = 4, active threads = 4, queued tasks = 0, completed tasks = 5]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2081) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:841) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1376) ~[na:na]
	at org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor$1.execute(ThreadPoolTaskExecutor.java:295) ~[spring-context-6.2.8.jar:6.2.8]
	at org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor.execute(ThreadPoolTaskExecutor.java:388) ~[spring-context-6.2.8.jar:6.2.8]
	... 18 common frames omitted

2025-07-01T21:48:24.430+05:30  INFO 45924 --- [SMS-Utility] [SMS-Thread-3] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 1, using thread:- SMS-Thread-3
2025-07-01T21:48:48.606+05:30  WARN 45924 --- [SMS-Utility] [HikariPool-1:housekeeper] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=48s181ms).
2025-07-01T21:48:48.645+05:30  INFO 45924 --- [SMS-Utility] [SMS-Thread-4] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 3, using thread:- SMS-Thread-4
2025-07-01T21:48:48.645+05:30  INFO 45924 --- [SMS-Utility] [SMS-Thread-2] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 2, using thread:- SMS-Thread-2
2025-07-01T21:48:48.645+05:30  INFO 45924 --- [SMS-Utility] [SMS-Thread-3] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 1, using thread:- SMS-Thread-3
2025-07-01T21:48:48.645+05:30  INFO 45924 --- [SMS-Utility] [SMS-Thread-1] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 4, using thread:- SMS-Thread-1
2025-07-01T21:48:48.646+05:30 ERROR 45924 --- [SMS-Utility] [scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

org.springframework.core.task.TaskRejectedException: ExecutorService in active state did not accept task: java.util.concurrent.CompletableFuture$AsyncSupply@358c57aa
	at org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor.execute(ThreadPoolTaskExecutor.java:391) ~[spring-context-6.2.8.jar:6.2.8]
	at java.base/java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1782) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:2005) ~[na:na]
	at com.example.SMS.Utility.service.SMSScheduler.scheduler(SMSScheduler.java:47) ~[classes/:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.runInternal(ScheduledMethodRunnable.java:130) ~[spring-context-6.2.8.jar:6.2.8]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.lambda$run$2(ScheduledMethodRunnable.java:124) ~[spring-context-6.2.8.jar:6.2.8]
	at io.micrometer.observation.Observation.observe(Observation.java:498) ~[micrometer-observation-1.15.1.jar:1.15.1]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:124) ~[spring-context-6.2.8.jar:6.2.8]
	at org.springframework.scheduling.config.Task$OutcomeTrackingRunnable.run(Task.java:85) ~[spring-context-6.2.8.jar:6.2.8]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.2.8.jar:6.2.8]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:358) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.CompletableFuture$AsyncSupply@358c57aa rejected from org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor$1@14b9817b[Running, pool size = 4, active threads = 1, queued tasks = 0, completed tasks = 9]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2081) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:841) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1376) ~[na:na]
	at org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor$1.execute(ThreadPoolTaskExecutor.java:295) ~[spring-context-6.2.8.jar:6.2.8]
	at org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor.execute(ThreadPoolTaskExecutor.java:388) ~[spring-context-6.2.8.jar:6.2.8]
	... 18 common frames omitted

2025-07-01T21:48:49.542+05:30  INFO 45924 --- [SMS-Utility] [SMS-Thread-4] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 2, using thread:- SMS-Thread-4
2025-07-01T21:48:49.542+05:30  INFO 45924 --- [SMS-Utility] [SMS-Thread-3] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 1, using thread:- SMS-Thread-3
2025-07-01T21:48:49.542+05:30  INFO 45924 --- [SMS-Utility] [SMS-Thread-2] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 3, using thread:- SMS-Thread-2
2025-07-01T21:48:49.542+05:30  INFO 45924 --- [SMS-Utility] [SMS-Thread-1] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 4, using thread:- SMS-Thread-1
2025-07-01T21:48:49.542+05:30 ERROR 45924 --- [SMS-Utility] [scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

org.springframework.core.task.TaskRejectedException: ExecutorService in active state did not accept task: java.util.concurrent.CompletableFuture$AsyncSupply@45b2e6f6
	at org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor.execute(ThreadPoolTaskExecutor.java:391) ~[spring-context-6.2.8.jar:6.2.8]
	at java.base/java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1782) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:2005) ~[na:na]
	at com.example.SMS.Utility.service.SMSScheduler.scheduler(SMSScheduler.java:47) ~[classes/:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.runInternal(ScheduledMethodRunnable.java:130) ~[spring-context-6.2.8.jar:6.2.8]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.lambda$run$2(ScheduledMethodRunnable.java:124) ~[spring-context-6.2.8.jar:6.2.8]
	at io.micrometer.observation.Observation.observe(Observation.java:498) ~[micrometer-observation-1.15.1.jar:1.15.1]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:124) ~[spring-context-6.2.8.jar:6.2.8]
	at org.springframework.scheduling.config.Task$OutcomeTrackingRunnable.run(Task.java:85) ~[spring-context-6.2.8.jar:6.2.8]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.2.8.jar:6.2.8]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:358) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.CompletableFuture$AsyncSupply@45b2e6f6 rejected from org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor$1@14b9817b[Running, pool size = 4, active threads = 4, queued tasks = 0, completed tasks = 13]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2081) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:841) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1376) ~[na:na]
	at org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor$1.execute(ThreadPoolTaskExecutor.java:295) ~[spring-context-6.2.8.jar:6.2.8]
	at org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor.execute(ThreadPoolTaskExecutor.java:388) ~[spring-context-6.2.8.jar:6.2.8]
	... 18 common frames omitted

2025-07-01T21:48:51.080+05:30  INFO 45924 --- [SMS-Utility] [SMS-Thread-2] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 3, using thread:- SMS-Thread-2
2025-07-01T21:48:51.080+05:30  INFO 45924 --- [SMS-Utility] [SMS-Thread-3] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 1, using thread:- SMS-Thread-3
2025-07-01T21:48:51.081+05:30  INFO 45924 --- [SMS-Utility] [SMS-Thread-4] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 4, using thread:- SMS-Thread-4
2025-07-01T21:48:51.080+05:30  INFO 45924 --- [SMS-Utility] [SMS-Thread-1] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 2, using thread:- SMS-Thread-1
2025-07-01T21:48:51.081+05:30 ERROR 45924 --- [SMS-Utility] [scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

org.springframework.core.task.TaskRejectedException: ExecutorService in active state did not accept task: java.util.concurrent.CompletableFuture$AsyncSupply@283ca54a
	at org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor.execute(ThreadPoolTaskExecutor.java:391) ~[spring-context-6.2.8.jar:6.2.8]
	at java.base/java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1782) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:2005) ~[na:na]
	at com.example.SMS.Utility.service.SMSScheduler.scheduler(SMSScheduler.java:47) ~[classes/:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.runInternal(ScheduledMethodRunnable.java:130) ~[spring-context-6.2.8.jar:6.2.8]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.lambda$run$2(ScheduledMethodRunnable.java:124) ~[spring-context-6.2.8.jar:6.2.8]
	at io.micrometer.observation.Observation.observe(Observation.java:498) ~[micrometer-observation-1.15.1.jar:1.15.1]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:124) ~[spring-context-6.2.8.jar:6.2.8]
	at org.springframework.scheduling.config.Task$OutcomeTrackingRunnable.run(Task.java:85) ~[spring-context-6.2.8.jar:6.2.8]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.2.8.jar:6.2.8]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:358) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.CompletableFuture$AsyncSupply@283ca54a rejected from org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor$1@14b9817b[Running, pool size = 4, active threads = 3, queued tasks = 0, completed tasks = 17]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2081) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:841) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1376) ~[na:na]
	at org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor$1.execute(ThreadPoolTaskExecutor.java:295) ~[spring-context-6.2.8.jar:6.2.8]
	at org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor.execute(ThreadPoolTaskExecutor.java:388) ~[spring-context-6.2.8.jar:6.2.8]
	... 18 common frames omitted

2025-07-01T21:51:20.462+05:30  WARN 45924 --- [SMS-Utility] [HikariPool-1:housekeeper] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=2m31s858ms).
2025-07-01T21:51:20.549+05:30  INFO 45924 --- [SMS-Utility] [SpringApplicationShutdownHook] o.s.b.w.e.tomcat.GracefulShutdown        : Commencing graceful shutdown. Waiting for active requests to complete
2025-07-01T21:51:20.552+05:30  INFO 45924 --- [SMS-Utility] [tomcat-shutdown] o.s.b.w.e.tomcat.GracefulShutdown        : Graceful shutdown complete
2025-07-01T21:51:20.720+05:30  INFO 45924 --- [SMS-Utility] [SMS-Thread-1] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 2, using thread:- SMS-Thread-1
2025-07-01T21:51:20.720+05:30  INFO 45924 --- [SMS-Utility] [SMS-Thread-4] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 3, using thread:- SMS-Thread-4
2025-07-01T21:51:20.720+05:30 ERROR 45924 --- [SMS-Utility] [scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

org.springframework.core.task.TaskRejectedException: ExecutorService in active state did not accept task: java.util.concurrent.CompletableFuture$AsyncSupply@1209aca4
	at org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor.execute(ThreadPoolTaskExecutor.java:391) ~[spring-context-6.2.8.jar:6.2.8]
	at java.base/java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1782) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:2005) ~[na:na]
	at com.example.SMS.Utility.service.SMSScheduler.scheduler(SMSScheduler.java:47) ~[classes/:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.runInternal(ScheduledMethodRunnable.java:130) ~[spring-context-6.2.8.jar:6.2.8]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.lambda$run$2(ScheduledMethodRunnable.java:124) ~[spring-context-6.2.8.jar:6.2.8]
	at io.micrometer.observation.Observation.observe(Observation.java:498) ~[micrometer-observation-1.15.1.jar:1.15.1]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:124) ~[spring-context-6.2.8.jar:6.2.8]
	at org.springframework.scheduling.config.Task$OutcomeTrackingRunnable.run(Task.java:85) ~[spring-context-6.2.8.jar:6.2.8]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.2.8.jar:6.2.8]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:358) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.CompletableFuture$AsyncSupply@1209aca4 rejected from org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor$1@14b9817b[Running, pool size = 4, active threads = 2, queued tasks = 0, completed tasks = 21]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2081) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:841) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1376) ~[na:na]
	at org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor$1.execute(ThreadPoolTaskExecutor.java:295) ~[spring-context-6.2.8.jar:6.2.8]
	at org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor.execute(ThreadPoolTaskExecutor.java:388) ~[spring-context-6.2.8.jar:6.2.8]
	... 18 common frames omitted

2025-07-01T21:51:20.720+05:30  INFO 45924 --- [SMS-Utility] [SMS-Thread-3] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 4, using thread:- SMS-Thread-3
2025-07-01T21:51:20.720+05:30  INFO 45924 --- [SMS-Utility] [SMS-Thread-2] c.e.SMS.Utility.service.SMSService       : Inside ProcessedSMS for :- 1, using thread:- SMS-Thread-2
2025-07-01T21:51:20.809+05:30  WARN 45924 --- [SMS-Utility] [reactor-http-nio-6] r.netty.http.client.HttpClientConnect    : [c7fc3875-1, L:/127.0.0.1:61963 ! R:localhost/127.0.0.1:9090] The connection observed an error

reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response

2025-07-01T21:51:20.815+05:30  WARN 45924 --- [SMS-Utility] [reactor-http-nio-3] r.netty.http.client.HttpClientConnect    : [049f0f82-1, L:/127.0.0.1:61975 ! R:localhost/127.0.0.1:9090] The connection observed an error

reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response

2025-07-01T21:51:20.826+05:30  WARN 45924 --- [SMS-Utility] [reactor-http-nio-4] r.netty.http.client.HttpClientConnect    : [68a3df4e-1, L:/127.0.0.1:61979 ! R:localhost/127.0.0.1:9090] The connection observed an error

reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response

2025-07-01T21:51:20.825+05:30 ERROR 45924 --- [SMS-Utility] [reactor-http-nio-3] c.e.SMS.Utility.service.SMSService       : While processing the rows error throwing:- Connection prematurely closed BEFORE response
2025-07-01T21:51:20.831+05:30 ERROR 45924 --- [SMS-Utility] [reactor-http-nio-4] c.e.SMS.Utility.service.SMSService       : While processing the rows error throwing:- Connection prematurely closed BEFORE response
2025-07-01T21:51:20.832+05:30 ERROR 45924 --- [SMS-Utility] [reactor-http-nio-6] c.e.SMS.Utility.service.SMSService       : While processing the rows error throwing:- Connection prematurely closed BEFORE response
2025-07-01T21:51:20.832+05:30  WARN 45924 --- [SMS-Utility] [reactor-http-nio-6] r.netty.http.client.HttpClientConnect    : [0a4602c6-1, L:/127.0.0.1:61974 ! R:localhost/127.0.0.1:9090] The connection observed an error

reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response

2025-07-01T21:51:20.834+05:30 ERROR 45924 --- [SMS-Utility] [reactor-http-nio-8] c.e.SMS.Utility.service.SMSService       : While processing the rows error throwing:- executor not accepting a task
2025-07-01T21:51:20.836+05:30 ERROR 45924 --- [SMS-Utility] [reactor-http-nio-6] c.e.SMS.Utility.service.SMSService       : While processing the rows error throwing:- Connection prematurely closed BEFORE response
2025-07-01T21:51:20.838+05:30 ERROR 45924 --- [SMS-Utility] [reactor-http-nio-1] c.e.SMS.Utility.service.SMSService       : While processing the rows error throwing:- executor not accepting a task
2025-07-01T21:51:20.846+05:30 ERROR 45924 --- [SMS-Utility] [reactor-http-nio-7] c.e.SMS.Utility.service.SMSService       : While processing the rows error throwing:- executor not accepting a task
2025-07-01T21:51:20.847+05:30 ERROR 45924 --- [SMS-Utility] [reactor-http-nio-2] c.e.SMS.Utility.service.SMSService       : While processing the rows error throwing:- executor not accepting a task
2025-07-01T21:51:22.923+05:30  INFO 45924 --- [SMS-Utility] [SpringApplicationShutdownHook] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2025-07-01T21:51:22.927+05:30  INFO 45924 --- [SMS-Utility] [SpringApplicationShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2025-07-01T21:51:22.931+05:30  INFO 45924 --- [SMS-Utility] [SpringApplicationShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2025-07-01T21:52:00.085+05:30  INFO 46149 --- [SMS-Utility] [main] c.e.SMS.Utility.SmsUtilityApplication    : Starting SmsUtilityApplication using Java 21.0.5 with PID 46149 (/Users/sakshamvaishya/Downloads/SMS-Utility/target/classes started by sakshamvaishya in /Users/sakshamvaishya/Downloads/SMS-Utility)
2025-07-01T21:52:00.088+05:30 DEBUG 46149 --- [SMS-Utility] [main] c.e.SMS.Utility.SmsUtilityApplication    : Running with Spring Boot v3.5.3, Spring v6.2.8
2025-07-01T21:52:00.093+05:30  INFO 46149 --- [SMS-Utility] [main] c.e.SMS.Utility.SmsUtilityApplication    : No active profile set, falling back to 1 default profile: "default"
2025-07-01T21:52:00.535+05:30  INFO 46149 --- [SMS-Utility] [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2025-07-01T21:52:00.618+05:30  INFO 46149 --- [SMS-Utility] [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 76 ms. Found 2 JPA repository interfaces.
2025-07-01T21:52:00.966+05:30  INFO 46149 --- [SMS-Utility] [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8080 (http)
2025-07-01T21:52:00.977+05:30  INFO 46149 --- [SMS-Utility] [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2025-07-01T21:52:00.977+05:30  INFO 46149 --- [SMS-Utility] [main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.42]
2025-07-01T21:52:01.015+05:30  INFO 46149 --- [SMS-Utility] [main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2025-07-01T21:52:01.015+05:30  INFO 46149 --- [SMS-Utility] [main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 884 ms
2025-07-01T21:52:01.109+05:30  INFO 46149 --- [SMS-Utility] [main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2025-07-01T21:52:01.141+05:30  INFO 46149 --- [SMS-Utility] [main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 6.6.18.Final
2025-07-01T21:52:01.158+05:30  INFO 46149 --- [SMS-Utility] [main] o.h.c.internal.RegionFactoryInitiator    : HHH000026: Second-level cache disabled
2025-07-01T21:52:01.324+05:30  INFO 46149 --- [SMS-Utility] [main] o.s.o.j.p.SpringPersistenceUnitInfo      : No LoadTimeWeaver setup: ignoring JPA class transformer
2025-07-01T21:52:01.342+05:30  INFO 46149 --- [SMS-Utility] [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2025-07-01T21:52:01.487+05:30  INFO 46149 --- [SMS-Utility] [main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@336e3be2
2025-07-01T21:52:01.487+05:30  INFO 46149 --- [SMS-Utility] [main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2025-07-01T21:52:01.527+05:30  INFO 46149 --- [SMS-Utility] [main] org.hibernate.orm.connections.pooling    : HHH10001005: Database info:
	Database JDBC URL [Connecting through datasource 'HikariDataSource (HikariPool-1)']
	Database driver: undefined/unknown
	Database version: 17.2
	Autocommit mode: undefined/unknown
	Isolation level: undefined/unknown
	Minimum pool size: undefined/unknown
	Maximum pool size: undefined/unknown
2025-07-01T21:52:02.019+05:30  INFO 46149 --- [SMS-Utility] [main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000489: No JTA platform available (set 'hibernate.transaction.jta.platform' to enable JTA platform integration)
2025-07-01T21:52:02.057+05:30  INFO 46149 --- [SMS-Utility] [main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2025-07-01T21:52:02.196+05:30  INFO 46149 --- [SMS-Utility] [main] o.s.d.j.r.query.QueryEnhancerFactory     : Hibernate is in classpath; If applicable, HQL parser will be used.
2025-07-01T21:52:02.329+05:30  INFO 46149 --- [SMS-Utility] [main] com.example.SMS.Utility.config.Config    : corePoolSize:-4, maxPoolSize:-4,queueCapacity:-0
2025-07-01T21:52:02.388+05:30  WARN 46149 --- [SMS-Utility] [main] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
2025-07-01T21:52:02.575+05:30  INFO 46149 --- [SMS-Utility] [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port 8080 (http) with context path '/'
2025-07-01T21:52:02.584+05:30  INFO 46149 --- [SMS-Utility] [main] c.e.SMS.Utility.SmsUtilityApplication    : Started SmsUtilityApplication in 2.887 seconds (process running for 3.234)
2025-07-01T23:41:50.590+05:30  WARN 46149 --- [SMS-Utility] [HikariPool-1:housekeeper] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1h49m48s979ms).
2025-07-01T23:41:50.697+05:30  INFO 46149 --- [SMS-Utility] [SpringApplicationShutdownHook] o.s.b.w.e.tomcat.GracefulShutdown        : Commencing graceful shutdown. Waiting for active requests to complete
2025-07-01T23:41:50.735+05:30  INFO 46149 --- [SMS-Utility] [tomcat-shutdown] o.s.b.w.e.tomcat.GracefulShutdown        : Graceful shutdown complete
2025-07-01T23:41:50.885+05:30  INFO 46149 --- [SMS-Utility] [scheduling-1] c.e.SMS.Utility.service.SMSScheduler     : No pending SMS to send to the user.
2025-07-01T23:41:50.904+05:30  INFO 46149 --- [SMS-Utility] [SpringApplicationShutdownHook] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2025-07-01T23:41:50.906+05:30  INFO 46149 --- [SMS-Utility] [SpringApplicationShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2025-07-01T23:41:50.950+05:30  INFO 46149 --- [SMS-Utility] [SpringApplicationShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
